[package]
name = "covid19ks"
version = "0.1.0"
authors = ["John Goerzen <jgoerzen@complete.org>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
rctree = "0.3.3"
chrono = "0.4"
plotters = {  version = "0.2.15", features = ["chrono"] }
