[package]
name = "covid19db"
version = "0.1.0"
authors = ["John Goerzen <jgoerzen@complete.org>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
julianday = "0.2"
