name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 11 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build
#      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
    - name: Execute
      run: cargo run --release
    - name: Compress
      run: gzip -9 covid19.db
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: covid19.db.gz
        path: covid19.db.gz
